function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of semilogy x data
%  YMATRIX1:  matrix of semilogy y data

%  Auto-generated by MATLAB on 29-May-2023 09:01:38

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple line objects using matrix input to semilogy
semilogy1 = semilogy(X1,YMatrix1,'Parent',axes1);
set(semilogy1(1),'DisplayName','$t = 0.1$');
set(semilogy1(2),'DisplayName','$t = 0.2$');
set(semilogy1(3),'DisplayName','$t = 0.3$');
set(semilogy1(4),'DisplayName','$t = 0.5$');
set(semilogy1(5),'DisplayName','$t = 1$');
set(semilogy1(6),'DisplayName','$t =  2$');
set(semilogy1(7),'DisplayName','$t = 5$');

xlim([0.7,1.3])
ylim([10,1.2*max(YMatrix1(1,:))])

% Create ylabel
ylabel('$Z_{SHH}$','FontSize',18,'Interpreter','latex');

% Create xlabel
xlabel('$\omega/\tilde{\omega}$ ','FontWeight','bold','FontSize',18,...
    'Interpreter','latex');

% Create title
title('impedance frequency responce of Su-Schriffer- Heeger circuit',...
    'FontSize',14,...
    'Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.7 1.3]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[10.6593864522549 16744.3827797221]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'YMinorTick','on','YScale','log');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.711926920960939 0.709744657580348 0.120667522464698 0.181095406360425],...
    'Interpreter','latex');